-- Refactor background structure to be more semantic and consistent
-- OLD structure (messy):
--   semantic.color.surface.page: contains color/gradient/image (mixed types)
--   background.videoUrl: video URL (inconsistent location)
--   background.wallpaper: dead code
--
-- NEW structure (clean):
--   background.type: "solid" | "gradient" | "image" | "video"
--   background.value: actual value (color hex | gradient CSS | image URL | video URL)
--   background.effects: blur, brightness, grayscale, overlayColor
--   semantic.color.surface.page: ONLY fallback color (always solid color)

-- This migration is for documentation only
-- Since all themes were deleted, no data migration needed
-- New themes will be created with the new structure automatically

-- Example of NEW structure:
-- {
--   "semantic": {
--     "color": {
--       "surface": {
--         "page": "#000000"  // ← Fallback color only
--       }
--     }
--   },
--   "background": {
--     "type": "gradient",
--     "value": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
--     "effects": {
--       "blur": 0,
--       "brightness": 100,
--       "grayscale": 0,
--       "overlayColor": "ref:tokens.color.overlay.10"
--     }
--   }
-- }
